INSERT INTO PARAMETER_MANAGEMENT_SERVICE.FAQ (
        ID_FAQ_CATEGORY,
        QUESTION_IDN,
        QUESTION_ENG,
        ANSWER_IDN,
        ANSWER_ENG,
        KEYWORDS,
        LIKES,
        DISLIKES,
        SEEN_BY_USER,
        CREATED_BY,
        CREATED_DATE,
        MODIFIED_BY,
        MODIFIED_DATE,
        IS_DELETED,
        STATUS,
        FAQ_CATEGORY_CODE,
        FAQ_CODE
    )
VALUES(
        821,
        'Berapa lama waktu yang diperlukan untuk pembentukan SID dan IFUA?',
        'Berapa lama waktu yang diperlukan untuk pembentukan SID dan IFUA?',
        'Lama waktu (SLA) pembuatan SID dan IFUA maksimal 2 Hari Bursa (Hari Kerja KSEI)',
        'Lama waktu (SLA) pembuatan SID dan IFUA maksimal 2 Hari Bursa (Hari Kerja KSEI)',
        'Reksa Dana, Registrasi',
        0,
        0,
        0,
        'ADMINPORTAL',
        TIMESTAMP '2023-05-15 04:29:32.740',
        NULL,
        NULL,
        0,
        0,
        'REGISTRASI',
        'REGISTRASI_FAQ_3'
    );