INSERT INTO PARAMETER_MANAGEMENT_SERVICE.FAQ (
        ID_FAQ_CATEGORY,
        QUESTION_IDN,
        QUESTION_ENG,
        ANSWER_IDN,
        ANSWER_ENG,
        KEYWORDS,
        LIKES,
        DISLIKES,
        SEEN_BY_USER,
        CREATED_BY,
        CREATED_DATE,
        MODIFIED_BY,
        MODIFIED_DATE,
        IS_DELETED,
        STATUS,
        FAQ_CATEGORY_CODE,
        FAQ_CODE
    )
VALUES(
        821,
        'Bagaimana cara mengetahui produk-produk reksa dana sebelum melakukan pendaftaran?',
        'Bagaimana cara mengetahui produk-produk reksa dana sebelum melakukan pendaftaran?',
        'Nasabah dapat melakukan eksplorasi produk reksadana untuk mengetahui kinerja produk dan manajer investasinya dan meninjau dokumen prospectus serta fund fact sheet',
        'Nasabah dapat melakukan eksplorasi produk reksadana untuk mengetahui kinerja produk dan manajer investasinya dan meninjau dokumen prospectus serta fund fact sheet',
        'Reksa Dana, Registrasi',
        0,
        0,
        0,
        'ADMINPORTAL',
        TIMESTAMP '2023-05-15 04:36:26.697',
        NULL,
        NULL,
        0,
        0,
        'REGISTRASI',
        'REGISTRASI_FAQ_7'
    );