INSERT INTO PARAMETER_MANAGEMENT_SERVICE.FAQ (
        ID_FAQ_CATEGORY,
        QUESTION_IDN,
        QUESTION_ENG,
        ANSWER_IDN,
        ANSWER_ENG,
        KEYWORDS,
        LIKES,
        DISLIKES,
        SEEN_BY_USER,
        CREATED_BY,
        CREATED_DATE,
        MODIFIED_BY,
        MODIFIED_DATE,
        IS_DELETED,
        STATUS,
        FAQ_CATEGORY_CODE,
        FAQ_CODE
    )
VALUES(
        821,
        'Apakah data cabang yang dipilih ketika registrasi bersifat wajib diisi?',
        'Apakah data cabang yang dipilih ketika registrasi bersifat wajib diisi?',
        'Iya, diisi menyesuaikan cabang terdekat dari lokasi nasabah. Cabang disini tidak akan berpengaruh pada transaksi reksa dana nasabah',
        'Iya, diisi menyesuaikan cabang terdekat dari lokasi nasabah. Cabang disini tidak akan berpengaruh pada transaksi reksa dana nasabah',
        'Reksa Dana, Registrasi',
        0,
        0,
        0,
        'ADMINPORTAL',
        TIMESTAMP '2023-05-15 04:37:40.257',
        NULL,
        NULL,
        0,
        0,
        'REGISTRASI',
        'REGISTRASI_FAQ_8'
    );