-- ADD COLUMN
ALTER TABLE PARAMETER_MANAGEMENT_SERVICE.RISK_PROFILE_QUESTION
ADD QUESTION_SESSION VARCHAR2(5);
-- DELETE COLUMN
ALTER TABLE PARAMETER_MANAGEMENT_SERVICE.RISK_PROFILE_QUESTION DROP COLUMN QUESTION_SESSION;