INSERT INTO PARAMETER_MANAGEMENT_SERVICE.FAQ (
        ID_FAQ_CATEGORY,
        QUESTION_IDN,
        QUESTION_ENG,
        ANSWER_IDN,
        ANSWER_ENG,
        KEYWORDS,
        LIKES,
        DISLIKES,
        SEEN_BY_USER,
        CREATED_BY,
        CREATED_DATE,
        MODIFIED_BY,
        MODIFIED_DATE,
        IS_DELETED,
        STATUS,
        FAQ_CATEGORY_CODE,
        FAQ_CODE
    )
VALUES(
        824,
        'Bagaimana caranya jika nasabah ingin melihat portofolio Reksa Dana yang mereka miliki?',
        'Bagaimana caranya jika nasabah ingin melihat portofolio Reksa Dana yang mereka miliki?',
        'Nasabah dapat masuk melalui menu Portofolio, lalu total portofolio nasabah beserta detail produk muncul pada halaman tersebut',
        'Nasabah dapat masuk melalui menu Portofolio, lalu total portofolio nasabah beserta detail produk muncul pada halaman tersebut',
        'Reksa Dana, Portfolio',
        0,
        0,
        0,
        'ADMINPORTAL',
        TIMESTAMP '2023-05-15 05:00:04.757',
        NULL,
        NULL,
        0,
        0,
        'PORTFOLIO',
        'PORTFOLIO_FAQ_1'
    );