INSERT INTO PARAMETER_MANAGEMENT_SERVICE.FAQ (
        ID_FAQ_CATEGORY,
        QUESTION_IDN,
        QUESTION_ENG,
        ANSWER_IDN,
        ANSWER_ENG,
        KEYWORDS,
        LIKES,
        DISLIKES,
        SEEN_BY_USER,
        CREATED_BY,
        CREATED_DATE,
        MODIFIED_BY,
        MODIFIED_DATE,
        IS_DELETED,
        STATUS,
        FAQ_CATEGORY_CODE,
        FAQ_CODE
    )
VALUES(
        824,
        'Apakah portfolio transaksi dicabang juga akan terakumulasi pada portfolio mobile banking?',
        'Apakah portfolio transaksi dicabang juga akan terakumulasi pada portfolio mobile banking?',
        'Iya, Portfolio yang muncul di mobile banking adalah keseluruhan portofolio nasabah baik yang dibeli via mobile banking maupun melalui cabang',
        'Iya, Portfolio yang muncul di mobile banking adalah keseluruhan portofolio nasabah baik yang dibeli via mobile banking maupun melalui cabang',
        'Reksa Dana, Portfolio',
        0,
        0,
        0,
        'ADMINPORTAL',
        TIMESTAMP '2023-05-15 05:01:32.870',
        NULL,
        NULL,
        0,
        0,
        'PORTFOLIO',
        'PORTFOLIO_FAQ_2'
    );