INSERT INTO PARAMETER_MANAGEMENT_SERVICE.FAQ (
        ID_FAQ_CATEGORY,
        QUESTION_IDN,
        QUESTION_ENG,
        ANSWER_IDN,
        ANSWER_ENG,
        KEYWORDS,
        LIKES,
        DISLIKES,
        SEEN_BY_USER,
        CREATED_BY,
        CREATED_DATE,
        MODIFIED_BY,
        MODIFIED_DATE,
        IS_DELETED,
        STATUS,
        FAQ_CATEGORY_CODE,
        FAQ_CODE
    )
VALUES(
        825,
        'Bagaimana jika profil risiko nasabah expired?',
        'Bagaimana jika profil risiko nasabah expired?',
        'Nasabah akan mendapatkan pop up transaksi apabila profil risiko expired dan nasabah diarahkan melakukan pengisian profil risiko',
        'Nasabah akan mendapatkan pop up transaksi apabila profil risiko expired dan nasabah diarahkan melakukan pengisian profil risiko',
        'Reksa Dana, Lainnya',
        0,
        0,
        0,
        'ADMINPORTAL',
        TIMESTAMP '2023-05-15 05:04:33.707',
        NULL,
        NULL,
        0,
        0,
        'LAINNYA',
        'LAINNYA_FAQ_2'
    );