INSERT INTO FAQ (
        faq_category_code,
        faq_code,
        question,
        answer,
        popular_order,
        created_by,
        created_date,
        modified_by,
        modified_date,
        is_deleted
    )
VALUES(
        'REKSADANA',
        'REKSADANA_FAQ_1',
        'Apa itu Reksa Dana?',
        'Adalah wadah yang menggabungkan modal dari banyak investor, berinvestasi pada beragam instrumen, serta dikelola secara profesional oleh perusahaan pengelola aset (Manajer Investasi)',
        1,
        'SYSTEM',
        TIMESTAMP '2023-05-15 03:34:21.860',
        NULL,
        NULL,
        FALSE
    ),
    (
        'REKSADANA',
        'REKSADANA_FAQ_2',
        'Apa keunggulan reksa dana bagi nasabah?',
        'Fleksibel (Banyak pilihan produk sesuai kebutuhan investasi)<br/>Likuid (Bisa dicairkan kapan saja, tanpa jangka waktu)<br/>Aman (Terdaftar dan diawasi OJK)<br/>Bebas pajak (Hasil investasi reksa dana tidak dipotong pajak)',
        2,
        'SYSTEM',
        TIMESTAMP '2023-05-15 03:43:29.927',
        NULL,
        NULL,
        FALSE
    ),
    (
        'REKSADANA',
        'REKSADANA_FAQ_4',
        'Apa Perbedaan Reksadana Syariah dan Konvensional?',
        'Syariah: Dikelola sesuai prinsip syariah. Investasi hanya pada Efek Syariah. Terdapat mekanisme pembersihan harta Non-Halal (Cleansing). Wajib dikelola oleh profesional yang mengerti kegiatan yang dilarang berdasarkan prinsip syariah. Konvensional: Dikelola tanpa memperhatikan prinsip syariah. Investasi pada Seluruh Efek. Tidak menggunakan konsep pembersihan harta. Tidak perlu profesional yang mengerti kegiatan yang dilarang berdasarkan prinsip syariah.',
        3,
        'SYSTEM',
        TIMESTAMP '2023-05-15 03:53:18.943',
        NULL,
        NULL,
        FALSE
    ),
    (
        'REKSADANA',
        'REKSADANA_FAQ_10',
        'Apakah produk reksa dana dan perusahaan investasi dijamin regulator?',
        'Dana investasi dikelola oleh perusahaan yang memiliki izin dan diawasi oleh Otoritas Jasa Keuangan (OJK).',
        10,
        'SYSTEM',
        TIMESTAMP '2023-05-15 04:07:21.653',
        NULL,
        NULL,
        FALSE
    ),
    (
        'REKSADANA',
        'REKSADANA_FAQ_11',
        'Apakah yang dimaksud dengan produk reksa dana pasar uang?',
        'Produk yang penempatan investasinya hanya pada instrumen pasar uang berjangka (<1 tahun) dan deposito. Risiko produk ini sangat kecil. Reksa Dana ini sangat baik untuk investor yang sangat konservatif dengan tujuan investasi jangka pendek (0-1 tahun), dan baru mulai belajar berinvestasi.',
        4,
        'SYSTEM',
        TIMESTAMP '2023-05-15 04:08:56.193',
        NULL,
        NULL,
        FALSE
    ),
    (
        'REKSADANA',
        'REKSADANA_FAQ_12',
        'Apakah yang dimaksud dengan produk reksa dana pendapatan tetap?',
        'Produk yang komposisi penempatan investasinya adalah minimal 80% Sukuk, sehingga tidak terlalu berfluktuasi. Risiko produk ini rendah dan potensi hasil juga relatif rendah. Reksa Dana Pendapatan Tetap baik untuk investor konservatif (1-3 tahun) dengan jangka waktu investasi pendek',
        5,
        'SYSTEM',
        TIMESTAMP '2023-05-15 04:11:57.327',
        NULL,
        NULL,
        FALSE
    ),
    (
        'REKSADANA',
        'REKSADANA_FAQ_13',
        'Apakah yang dimaksud dengan produk reksa dana pasar campuran?',
        'Produk yang penempatan investasinya menggunakan Porsi berimbang antara saham dan sukuk sehingga berfluktuasi moderat. Risiko produk ini sedang dan potensi hasil sedang. Reksa Dana Campuran baik untuk investor moderat (3–5 tahun) yang ingin menikmati potensi dari saham dan sukuk.',
        6,
        'SYSTEM',
        TIMESTAMP '2023-05-15 04:14:40.283',
        NULL,
        NULL,
        FALSE
    ),
    (
        'REKSADANA',
        'REKSADANA_FAQ_14',
        'Apakah yang dimaksud dengan produk reksa dana saham?',
        'Produk yang penempatan investasinya adalah minimal 80% saham sehingga berfluktuasi dengan agresif. Risiko produk ini tinggi dan potensi hasil juga tinggi. Reksa Dana Saham baik untuk investasi jangka panjang (5->10 tahun).',
        7,
        'SYSTEM',
        TIMESTAMP '2023-05-15 04:16:30.800',
        NULL,
        NULL,
        FALSE
    ),
    (
        'REKSADANA',
        'REKSADANA_FAQ_15',
        'Fitur apa aja yang tersedia pada menu reksa dana saat ini?',
        'Registrasi, Pembelian, Penjualan, dan Portfolio. Untuk fitur History, Switching dan Beli Rutin akan dirilis pada fase berikutnya',
        8,
        'SYSTEM',
        TIMESTAMP '2023-05-15 04:18:01.930',
        NULL,
        NULL,
        FALSE
    ),
    (
        'REKSADANA',
        'REKSADANA_FAQ_16',
        'Apakah ada jam operasional transaksi di mobile apps?',
        'Tidak ada, seluruh fitur dapat diakses dan ditransaksikan selama 24 jam/7 hari',
        9,
        'SYSTEM',
        TIMESTAMP '2023-05-15 04:19:23.840',
        NULL,
        NULL,
        FALSE
    );