INSERT INTO PARAMETER_MANAGEMENT_SERVICE.ACCOUNT_PRODUCT (
    ACCOUNT_TYPE,
    CREATED_BY,
    CREATED_DATE,
    CURRENCY_CODE,
    ISDELETED,
    END_DATE,
    INQUIRY_ALLOWED,
    MIN_BALANCE,
    MIN_INITIAL_DEPOSIT,
    MODIFIED_BY,
    MODIFIED_DATE,
    OPEN_ACCOUNT_ALLOWED,
    PRIMARY_ACCOUNT_ALLOWED,
    PRIORITY,
    PRODUCT_CODE,
    PRODUCT_CODE_NUMBER,
    PRODUCT_IMAGE,
    PRODUCT_INFO_ENG,
    PRODUCT_INFO_IDN,
    PRODUCT_INFO_LINK,
    PRODUCT_INFO_TNC_ENG,
    PRODUCT_INFO_TNC_IDN,
    PRODUCT_NAME,
    PRODUCT_SUBJECT_ENG,
    PRODUCT_SUBJECT_IDN,
    SAVING_TYPE,
    SOF_ALLOWED,
    SOF_EDEPOSITO,
    START_DATE,
    PRODUCT_DESCRIPTION_IDN,
    PRODUCT_DESCRIPTION_ENG,
    PRODUCT_SHORT_DESCRIPTION_IDN,
    PRODUCT_SHORT_DESCRIPTION_ENG,
    MULTIPLE_ALLOWED,
    PRODUCT_FEATURE_IDN,
    PRODUCT_FEATURE_ENG,
    NTB_ALLOWED,
    ETB_ALLOWED,
    AUTOSAVE_ALLOWED,
    EVENT_CODE,
    AUTOSAVE_MIN_DEPOSIT,
    AUTOSAVE_TITLE_IDN,
    AUTOSAVE_TITLE_ENG,
    AUTOSAVE_DESCRIPTION_IDN,
    AUTOSAVE_DESCRIPTION_ENG,
    BUREKOL_OPEN_ALLOWED,
    PRODUCT_NAME_CARD,
    PRODUCT_DESCRIPTION_CARD,
    PRODUCT_SHORT_DESC_CARD,
    PRODUCT_DESCRIPTION_CARD_ENG,
    PRODUCT_SHORT_DESC_CARD_ENG
  )
VALUES(
    'SA',
    'SYSTEM',
    TIMESTAMP '2023-05-04 10:10:30.000000',
    NULL,
    0,
    NULL,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    1,
    0,
    NULL,
    'REKSADANA',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Reksa Dana',
    NULL,
    NULL,
    NULL,
    1,
    0,
    NULL,
    'Investasi lebih mudah untuk masa depan yang lebih berkah',
    'Investasi lebih mudah untuk masa depan yang lebih berkah',
    'Investasi mulai dari Rp 100.000<br/>Likuiditas yang tinggi<br/>Reksa Dana secara syariah',
    'Investasi mulai dari Rp 100.000<br/>Likuiditas yang tinggi<br/>Reksa Dana secara syariah',
    1,
    NULL,
    NULL,
    1,
    1,
    1,
    NULL,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    'Reksa Dana',
    'Investasi lebih mudah untuk masa depan yang lebih berkah',
    'Investasi mulai dari Rp 100.000<br/>Likuiditas yang tinggi<br/>Reksa Dana secara syariah',
    'Investasi lebih mudah untuk masa depan yang lebih berkah',
    'Investasi mulai dari Rp 100.000<br/>Likuiditas yang tinggi<br/>Reksa Dana secara syariah'
  );