INSERT INTO PARAMETER_MANAGEMENT_SERVICE.FAQ (
        ID_FAQ_CATEGORY,
        QUESTION_IDN,
        QUESTION_ENG,
        ANSWER_IDN,
        ANSWER_ENG,
        KEYWORDS,
        LIKES,
        DISLIKES,
        SEEN_BY_USER,
        CREATED_BY,
        CREATED_DATE,
        MODIFIED_BY,
        MODIFIED_DATE,
        IS_DELETED,
        STATUS,
        FAQ_CATEGORY_CODE,
        FAQ_CODE
    )
VALUES(
        801,
        'Apa itu Reksa Dana?',
        'Apa itu Reksa Dana?',
        'Adalah wadah yang menggabungkan modal dari banyak investor, berinvestasi pada beragam instrumen, serta dikelola secara profesional oleh perusahaan pengelola aset (Manajer Investasi)',
        'Adalah wadah yang menggabungkan modal dari banyak investor, berinvestasi pada beragam instrumen, serta dikelola secara profesional oleh perusahaan pengelola aset (Manajer Investasi)',
        'Reksa Dana',
        0,
        0,
        0,
        'ADMINPORTAL',
        TIMESTAMP '2023-05-15 03:34:21.860',
        NULL,
        NULL,
        0,
        0,
        'REKSADANA',
        'REKSADANA_FAQ_1'
    );