INSERT INTO PARAMETER_MANAGEMENT_SERVICE.FAQ (
        ID_FAQ_CATEGORY,
        QUESTION_IDN,
        QUESTION_ENG,
        ANSWER_IDN,
        ANSWER_ENG,
        KEYWORDS,
        LIKES,
        DISLIKES,
        SEEN_BY_USER,
        CREATED_BY,
        CREATED_DATE,
        MODIFIED_BY,
        MODIFIED_DATE,
        IS_DELETED,
        STATUS,
        FAQ_CATEGORY_CODE,
        FAQ_CODE
    )
VALUES(
        801,
        'Apa keunggulan reksa dana bagi nasabah?',
        'Apa keunggulan reksa dana bagi nasabah?',
        'Fleksibel (Banyak pilihan produk sesuai kebutuhan investasi)<br/>Likuid (Bisa dicairkan kapan saja, tanpa jangka waktu)<br/>Aman (Terdaftar dan diawasi OJK)<br/>Bebas pajak (Hasil investasi reksa dana tidak dipotong pajak)',
        'Fleksibel (Banyak pilihan produk sesuai kebutuhan investasi)<br/>Likuid (Bisa dicairkan kapan saja, tanpa jangka waktu)<br/>Aman (Terdaftar dan diawasi OJK)<br/>Bebas pajak (Hasil investasi reksa dana tidak dipotong pajak)',
        'Reksa Dana',
        0,
        0,
        0,
        'ADMINPORTAL',
        TIMESTAMP '2023-05-15 03:43:29.927',
        NULL,
        NULL,
        0,
        0,
        'REKSADANA',
        'REKSADANA_FAQ_2'
    );