INSERT INTO PARAMETER_MANAGEMENT_SERVICE.FAQ (
        ID_FAQ_CATEGORY,
        QUESTION_IDN,
        QUESTION_ENG,
        ANSWER_IDN,
        ANSWER_ENG,
        KEYWORDS,
        LIKES,
        DISLIKES,
        SEEN_BY_USER,
        CREATED_BY,
        CREATED_DATE,
        MODIFIED_BY,
        MODIFIED_DATE,
        IS_DELETED,
        STATUS,
        FAQ_CATEGORY_CODE,
        FAQ_CODE
    )
VALUES(
        801,
        'Apa saja risiko melakukan investasi reksa dana?',
        'Apa saja risiko melakukan investasi reksa dana?',
        'Risiko Likuiditas yaitu penundaan pencairan dana <br/>Risiko berkurangnya nilai investasi <br/>Risiko Perubahan Kondisi Politik dan Ekonomi <br/>Risiko Wanprestasi yaitu kondisi dimana penerbit efek tidak dapat memenuhi kewajibannya',
        'Risiko Likuiditas yaitu penundaan pencairan dana <br/>Risiko berkurangnya nilai investasi <br/>Risiko Perubahan Kondisi Politik dan Ekonomi <br/>Risiko Wanprestasi yaitu kondisi dimana penerbit efek tidak dapat memenuhi kewajibannya',
        'Reksa Dana',
        0,
        0,
        0,
        'ADMINPORTAL',
        TIMESTAMP '2023-05-15 03:58:15.960',
        NULL,
        NULL,
        0,
        0,
        'REKSADANA',
        'REKSADANA_FAQ_7'
    );