INSERT INTO PARAMETER_MANAGEMENT_SERVICE.FAQ (
        ID_FAQ_CATEGORY,
        QUESTION_IDN,
        QUESTION_ENG,
        ANSWER_IDN,
        ANSWER_ENG,
        KEYWORDS,
        LIKES,
        DISLIKES,
        SEEN_BY_USER,
        CREATED_BY,
        CREATED_DATE,
        MODIFIED_BY,
        MODIFIED_DATE,
        IS_DELETED,
        STATUS,
        FAQ_CATEGORY_CODE,
        FAQ_CODE
    )
VALUES(
        801,
        'Berapa lama waktu investasi reksa dana?',
        'Berapa lama waktu investasi reksa dana?',
        'Tidak ada jangka waktu minimum. Nasabah dapat melakukan pembelian dan penjualan unit kapanpun. <br/>Sebagai edukasi: Sebaiknya investasi Reksa Dana dilakukan untuk rencana jangka waktu menengah hingga panjang.',
        'Tidak ada jangka waktu minimum. Nasabah dapat melakukan pembelian dan penjualan unit kapanpun. <br/>Sebagai edukasi: Sebaiknya investasi Reksa Dana dilakukan untuk rencana jangka waktu menengah hingga panjang.',
        'Reksa Dana',
        0,
        0,
        0,
        'ADMINPORTAL',
        TIMESTAMP '2023-05-15 03:59:55.533',
        NULL,
        NULL,
        0,
        0,
        'REKSADANA',
        'REKSADANA_FAQ_8'
    );