INSERT INTO PARAMETER_MANAGEMENT_SERVICE.FAQ (
        ID_FAQ_CATEGORY,
        QUESTION_IDN,
        QUESTION_ENG,
        ANSWER_IDN,
        ANSWER_ENG,
        KEYWORDS,
        LIKES,
        DISLIKES,
        SEEN_BY_USER,
        CREATED_BY,
        CREATED_DATE,
        MODIFIED_BY,
        MODIFIED_DATE,
        IS_DELETED,
        STATUS,
        FAQ_CATEGORY_CODE,
        FAQ_CODE
    )
VALUES(
        801,
        'Apakah nasabah harus memilih saham dan obligasi sendiri?',
        'Apakah nasabah harus memilih saham dan obligasi sendiri?',
        'Tidak perlu. Manajer Investasi akan melakukan pemilihan dan penempatan produk saham dan obligasi tersebut. Nasabah cukup memilih ingin fitur reksa dana saham, Pendapatan Tetap, Campuran atau Pasar Uang.',
        'Tidak perlu. Manajer Investasi akan melakukan pemilihan dan penempatan produk saham dan obligasi tersebut. Nasabah cukup memilih ingin fitur reksa dana saham, Pendapatan Tetap, Campuran atau Pasar Uang.',
        'Reksa Dana',
        0,
        0,
        0,
        'ADMINPORTAL',
        TIMESTAMP '2023-05-15 04:06:14.990',
        NULL,
        NULL,
        0,
        0,
        'REKSADANA',
        'REKSADANA_FAQ_9'
    );