INSERT INTO PARAMETER_MANAGEMENT_SERVICE.FAQ (
        ID_FAQ_CATEGORY,
        QUESTION_IDN,
        QUESTION_ENG,
        ANSWER_IDN,
        ANSWER_ENG,
        KEYWORDS,
        LIKES,
        DISLIKES,
        SEEN_BY_USER,
        CREATED_BY,
        CREATED_DATE,
        MODIFIED_BY,
        MODIFIED_DATE,
        IS_DELETED,
        STATUS,
        FAQ_CATEGORY_CODE,
        FAQ_CODE
    )
VALUES(
        801,
        'Apakah produk reksa dana dan perusahaan investasi dijamin regulator?',
        'Apakah produk reksa dana dan perusahaan investasi dijamin regulator?',
        'Dana investasi dikelola oleh perusahaan yang memiliki izin dan diawasi oleh Otoritas Jasa Keuangan (OJK).',
        'Dana investasi dikelola oleh perusahaan yang memiliki izin dan diawasi oleh Otoritas Jasa Keuangan (OJK).',
        'Reksa Dana',
        0,
        0,
        0,
        'ADMINPORTAL',
        TIMESTAMP '2023-05-15 04:07:21.653',
        NULL,
        NULL,
        0,
        0,
        'REKSADANA',
        'REKSADANA_FAQ_10'
    );