INSERT INTO PARAMETER_MANAGEMENT_SERVICE.FAQ (
        ID_FAQ_CATEGORY,
        QUESTION_IDN,
        QUESTION_ENG,
        ANSWER_IDN,
        ANSWER_ENG,
        KEYWORDS,
        LIKES,
        DISLIKES,
        SEEN_BY_USER,
        CREATED_BY,
        CREATED_DATE,
        MODIFIED_BY,
        MODIFIED_DATE,
        IS_DELETED,
        STATUS,
        FAQ_CATEGORY_CODE,
        FAQ_CODE
    )
VALUES(
        801,
        'Apakah ada jam operasional transaksi di mobile apps?',
        'Apakah ada jam operasional transaksi di mobile apps?',
        'Tidak ada, seluruh fitur dapat diakses dan ditransaksikan selama 24 jam/7 hari',
        'Tidak ada, seluruh fitur dapat diakses dan ditransaksikan selama 24 jam/7 hari',
        'Reksa Dana',
        0,
        0,
        0,
        'ADMINPORTAL',
        TIMESTAMP '2023-05-15 04:19:23.840',
        NULL,
        NULL,
        0,
        0,
        'REKSADANA',
        'REKSADANA_FAQ_16'
    );