INSERT INTO PARAMETER_MANAGEMENT_SERVICE.FAQ (
        ID_FAQ_CATEGORY,
        QUESTION_IDN,
        QUESTION_ENG,
        ANSWER_IDN,
        ANSWER_ENG,
        KEYWORDS,
        LIKES,
        DISLIKES,
        SEEN_BY_USER,
        CREATED_BY,
        CREATED_DATE,
        MODIFIED_BY,
        MODIFIED_DATE,
        IS_DELETED,
        STATUS,
        FAQ_CATEGORY_CODE,
        FAQ_CODE
    )
VALUES(
        822,
        'Apa saja poin informasi yang dapat diperhatikan nasabah ketika melakukan proses pembelian reksa dana?',
        'Apa saja poin informasi yang dapat diperhatikan nasabah ketika melakukan proses pembelian reksa dana?',
        'Nasabah dapat mengetahui informasi ketentuan produk, kinerja produk dalam kurun waktu tertentu, dan informasi detail performa manajer investasi pada dokumen prospectus serta fund fact sheet dan NAV (harga reksadana)',
        'Nasabah dapat mengetahui informasi ketentuan produk, kinerja produk dalam kurun waktu tertentu, dan informasi detail performa manajer investasi pada dokumen prospectus serta fund fact sheet dan NAV (harga reksadana)',
        'Reksa Dana, Beli',
        0,
        0,
        0,
        'ADMINPORTAL',
        TIMESTAMP '2023-05-15 04:43:17.670',
        NULL,
        NULL,
        0,
        0,
        'BELI_REKSADANA',
        'BELI_REKSADANA_FAQ_2'
    );