UPDATE PARAMETER_MANAGEMENT_SERVICE.SYSTEM_PARAMETER
SET CREATED_BY = 'SYSTEM',
    CREATED_DATE = TIMESTAMP '2023-04-28 15:49:43.130234',
    DESCRIPTION = 'Check Version iOS',
    IS_ENCRYPTED = 1,
    MODIFIED_BY = NULL,
    MODIFIED_DATE = NULL,
    MODULE = 'CHECK_VERSION',
    NAME = 'IOS_BUILD_NUMBER',
    VALUE = '610',
    IS_DELETED = 0
WHERE MODULE = 'CHECK_VERSION' AND NAME = 'IOS_BUILD_NUMBER';