INSERT INTO PARAMETER_MANAGEMENT_SERVICE.FAQ_CATEGORY (
        CREATED_BY,
        CREATED_DATE,
        MODIFIED_BY,
        MODIFIED_DATE,
        NAME_IDN,
        NAME_ENG,
        IMAGE_URL,
        PRIORITY,
        IS_DELETED,
        STATUS,
        CATEGORY_CODE,
        MODULE
    )
VALUES(
        'ADMIN',
        TIMESTAMP '2023-05-14 14:41:24.520',
        NULL,
        NULL,
        'Reksadana',
        'Reksadana',
        'http://mf8.myinfosys.net:7005/bsi/assets/FaqCategory/FaqCategoryQCV6ThuMay0410:50:22WIB2023.png',
        1,
        0,
        '1',
        NULL,
        NULL,
        'REKSADANA',
        'REKSADANA'
    );