ALTER TABLE PARAMETER_MANAGEMENT_SERVICE.FAQ
ADD (
        FAQ_CATEGORY_CODE VARCHAR(255) NULL,
        FAQ_CODE VARCHAR(255) NULL
    );

    --  CONSTRAINT CATEGORY_CODE BELAKANGAN AJA, TAKUTNYA ADA DATA DI TABLE FAQ, TAPI TIDAK ADA CATEGORY CODE DI PARENT NYA